# Uncoupled, HAR forcing
_config_key: 'har'
display_name: 'HBV HAR'
color: '#d62728'
coupled: false
glacier_source: 'none'
meteo_source: 'HAR'

# Only HBV has internal glacier model for uncoupled mode
compatible_models: [HBV]
