# =============================================================================
# Server environment paths (GIUB server)
# =============================================================================

main_dir: '/home/jberg@giub.local/Raven_world'
meteo_dir: '/home/jberg@giub.local/Raven_world/01_data/meteo/Indus-Era5'
meteo_har_dir: '/home/jberg@giub.local/Raven_world/01_data/meteo/HAR'
cmip6_dir: '/home/jberg@giub.local/Raven_world/01_data/CMIP6'
raven_executable: '/home/jberg@giub.local/RavenHydroFramework/build/Raven'
